// <auto-generated />
using System;
using Domains_Scraper.Entity_Framework_folder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domains_Scraper.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20220213150650_ReAddOrganicDataId")]
    partial class ReAddOrganicDataId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domains_Scraper.Models.AllTimeOrganicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("OrganicDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganicDataId")
                        .IsUnique();

                    b.ToTable("AllTimeOrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.BacklinkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("FormLinks")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameLinks")
                        .HasColumnType("bigint");

                    b.Property<long>("ImageLinks")
                        .HasColumnType("bigint");

                    b.Property<int?>("SemrushDomainId")
                        .HasColumnType("int");

                    b.Property<long>("TextLinks")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BacklinkType");
                });

            modelBuilder.Entity("Domains_Scraper.Models.FollowLinksVsNoFollowLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("FollowLinks")
                        .HasColumnType("bigint");

                    b.Property<long>("NotFollowLinks")
                        .HasColumnType("bigint");

                    b.Property<int?>("SemrushDomainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FollowLinksVsNoFollowLink");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OneYearOrganicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("OrganicDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganicDataId")
                        .IsUnique();

                    b.ToTable("OneYearOrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicChartData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AllTimeOrganicDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ElevenToTwenty")
                        .HasColumnType("bigint");

                    b.Property<long>("FiftyOneToOneHundred")
                        .HasColumnType("bigint");

                    b.Property<long>("FourToTen")
                        .HasColumnType("bigint");

                    b.Property<int?>("OneYearOrganicDataId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganicDataId")
                        .HasColumnType("int");

                    b.Property<long>("TopThree")
                        .HasColumnType("bigint");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<long>("TwentyOneToFifty")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AllTimeOrganicDataId");

                    b.HasIndex("OneYearOrganicDataId");

                    b.HasIndex("OrganicDataId");

                    b.ToTable("OrganicChartData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("OrganicKeywords")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganicTraffic")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicTrafficAndKeywordsByCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<long>("KeyWordsValue")
                        .HasColumnType("bigint");

                    b.Property<long>("OranicTraficValue")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrganicDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganicDataId");

                    b.ToTable("OrganicTrafficAndKeywordsByCountry");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicTrafficChartData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AllTimeOrganicDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OneYearOrganicDataId")
                        .HasColumnType("int");

                    b.Property<long>("OrganicTrafficValue")
                        .HasColumnType("bigint");

                    b.Property<long>("PaidTrafficValue")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AllTimeOrganicDataId");

                    b.HasIndex("OneYearOrganicDataId");

                    b.ToTable("OrganicTrafficChartData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.SemrushDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("AuthorityScore")
                        .HasColumnType("bigint");

                    b.Property<int?>("BacklinkTypeId")
                        .HasColumnType("int");

                    b.Property<long>("Backlinks")
                        .HasColumnType("bigint");

                    b.Property<int?>("FollowLinksVsNotFollowLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("OrganicDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacklinkTypeId");

                    b.HasIndex("FollowLinksVsNotFollowLinkId");

                    b.HasIndex("OrganicDataId");

                    b.ToTable("SemrushDomain");
                });

            modelBuilder.Entity("Domains_Scraper.Models.AllTimeOrganicData", b =>
                {
                    b.HasOne("Domains_Scraper.Models.OrganicData", "OrganicData")
                        .WithOne("AllTimeOrganicData")
                        .HasForeignKey("Domains_Scraper.Models.AllTimeOrganicData", "OrganicDataId");

                    b.Navigation("OrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OneYearOrganicData", b =>
                {
                    b.HasOne("Domains_Scraper.Models.OrganicData", "OrganicData")
                        .WithOne("OneYearOrganicData")
                        .HasForeignKey("Domains_Scraper.Models.OneYearOrganicData", "OrganicDataId");

                    b.Navigation("OrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicChartData", b =>
                {
                    b.HasOne("Domains_Scraper.Models.AllTimeOrganicData", "AllTimeOrganicData")
                        .WithMany("AllTimeOrganicKeyWordsChartData")
                        .HasForeignKey("AllTimeOrganicDataId");

                    b.HasOne("Domains_Scraper.Models.OneYearOrganicData", "OneYearOrganicData")
                        .WithMany("OneYearOrganicKeyWordsChartData")
                        .HasForeignKey("OneYearOrganicDataId");

                    b.HasOne("Domains_Scraper.Models.OrganicData", null)
                        .WithMany("OrganicPositionsDistrubution")
                        .HasForeignKey("OrganicDataId");

                    b.Navigation("AllTimeOrganicData");

                    b.Navigation("OneYearOrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicTrafficAndKeywordsByCountry", b =>
                {
                    b.HasOne("Domains_Scraper.Models.OrganicData", "OrganicData")
                        .WithMany("OrganicTrafficAndKeywordsByCountry")
                        .HasForeignKey("OrganicDataId");

                    b.Navigation("OrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicTrafficChartData", b =>
                {
                    b.HasOne("Domains_Scraper.Models.AllTimeOrganicData", "AllTimeOrganicData")
                        .WithMany("AllTimeOrganicTrafficChartData")
                        .HasForeignKey("AllTimeOrganicDataId");

                    b.HasOne("Domains_Scraper.Models.OneYearOrganicData", "OneYearOrganicData")
                        .WithMany("OneYearOrganicTrafficChartData")
                        .HasForeignKey("OneYearOrganicDataId");

                    b.Navigation("AllTimeOrganicData");

                    b.Navigation("OneYearOrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.SemrushDomain", b =>
                {
                    b.HasOne("Domains_Scraper.Models.BacklinkType", "BacklinkType")
                        .WithMany()
                        .HasForeignKey("BacklinkTypeId");

                    b.HasOne("Domains_Scraper.Models.FollowLinksVsNoFollowLink", "FollowLinksVsNotFollowLink")
                        .WithMany()
                        .HasForeignKey("FollowLinksVsNotFollowLinkId");

                    b.HasOne("Domains_Scraper.Models.OrganicData", "OrganicData")
                        .WithMany()
                        .HasForeignKey("OrganicDataId");

                    b.Navigation("BacklinkType");

                    b.Navigation("FollowLinksVsNotFollowLink");

                    b.Navigation("OrganicData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.AllTimeOrganicData", b =>
                {
                    b.Navigation("AllTimeOrganicKeyWordsChartData");

                    b.Navigation("AllTimeOrganicTrafficChartData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OneYearOrganicData", b =>
                {
                    b.Navigation("OneYearOrganicKeyWordsChartData");

                    b.Navigation("OneYearOrganicTrafficChartData");
                });

            modelBuilder.Entity("Domains_Scraper.Models.OrganicData", b =>
                {
                    b.Navigation("AllTimeOrganicData");

                    b.Navigation("OneYearOrganicData");

                    b.Navigation("OrganicPositionsDistrubution");

                    b.Navigation("OrganicTrafficAndKeywordsByCountry");
                });
#pragma warning restore 612, 618
        }
    }
}
